---
- name: Get Device data
  hosts: all
  gather_facts: no
  connection: local

  tasks:
  - name: Get data from device
    napalm_get_facts:
      hostname={{ip}}
      username={{user}}
      dev_os={{os}}
      password={{passwd}}
      filter='facts,interfaces'
    register: result

  - name: print data
    debug: var=result
